##################################################################
###                          Podfile                           ###
##################################################################

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'Lleida.net' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 0.9'
end
