##################################################################
###                          Podfile                           ###
##################################################################

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.5.4'
pod 'MBProgressHUD', '~> 0.9'